#!/bin/bash

echo "Enter username:"
read varname
echo  hello $varname
echo "Enter e-mail:"
read varemail
echo  the email is $varemail
echo "enter name of repository"
read varrepository
git clone https://github.com/$varname/$varrepository
git config --global user.name $varname
echo username:
git config --global user.name 
git config --global user.email $varemail
echo e-mail:
git config --global user.email
git status
