#!/bin/bash

echo "Enter username:"
read varname

echo  hello $varname
echo "Enter e-mail:"
read varemail
echo  the email is $varemail
echo "enter name of repository"
read varrepository
git clone https://github.com/$varname/$varrepository
cd $varrepository/

git config --local user.name $varname
git config --local user.email $varemail

git status

echo "Set up complete."
